SELECT * FROM customers LIMIT 20;

--Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amt) as revenue
 from customers
 group by gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id , purchase_amt   
from customers
where discount_applied = 'Yes' and purchase_amt >= (select AVG(purchase_amt) from customers);

--Q3. Which are the top 5 products with the highest average review rating?
select  item_purchased , round(AVG(review_rating:: numeric ),2) as "Review_Rating"
from customers 
group by item_purchased  
order by   AVG(review_rating) desc
limit 5;

--Q4. Compare the average purchase amounts between Standard and Express shipping.
select shipping_type,  ROUND(AVG(purchase_amt),2)
from customers
where shipping_type in ('Free Shipping','Express')
group by shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
 select subscription_status, 
 ROUND(AVG(purchase_amt),2) as average_spent ,
 SUM(purchase_amt) as total_revenue
 from customers
 group by subscription_status;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased , ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END )*100/COUNT(*),2 ) AS discount_percentage
FROM customers
GROUP BY item_purchased
ORDER BY discount_percentage  DESC 
LIMIT 5;
   
--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.


--Q8. What are the top 3 most purchased products within each category?


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

--Q10. What is the revenue contribution of each age group?

--Q11. Which category generated the highest total revenue?

--Q12. What is the average purchase amount by age group and gender?

--Q13. Which state/location has the highest number of customers and revenue?

--Q14. Find the top 10 customers with the highest total spending.

--Q15. Which payment method is used most frequently and what is its total revenue contribution?